// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MachineJob;

#nullable disable

namespace MachineJob.Migrations
{
    [DbContext(typeof(DatabaseWriteContext))]
    partial class DatabaseWriteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MachineJob.DatabaseWriteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Value1")
                        .HasColumnType("double");

                    b.Property<double?>("Value10")
                        .HasColumnType("double");

                    b.Property<double?>("Value2")
                        .HasColumnType("double");

                    b.Property<double?>("Value3")
                        .HasColumnType("double");

                    b.Property<double?>("Value4")
                        .HasColumnType("double");

                    b.Property<double?>("Value5")
                        .HasColumnType("double");

                    b.Property<double?>("Value6")
                        .HasColumnType("double");

                    b.Property<double?>("Value7")
                        .HasColumnType("double");

                    b.Property<double?>("Value8")
                        .HasColumnType("double");

                    b.Property<double?>("Value9")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("DatabaseWrites");
                });
#pragma warning restore 612, 618
        }
    }
}
